In [1]:
import numpy as np

In [2]:
import math

In [3]:
a = np.array([1,2,3])
a.ndim

1

In [5]:
b = np.array([[1,2,3], [4,5,6]])
b.ndim

2

In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int32')

In [10]:
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [11]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
e = np.ones((2,3))
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.rand(2,3)

array([[0.12095586, 0.42823712, 0.83013704],
       [0.73310537, 0.35507748, 0.5441795 ]])